config/routes.rb
Rails.application.routes.draw do
  get 'private_wikis/index'

  get 'private_wikis/show'

  get 'private_wikis/create'

  get 'private_wikis/destroy'

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis

  get 'users/new'

  get 'users/show'

  get 'users/create'

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root "welcome#index"
end

app/models/amount.rb
class Amount < ActiveRecord::Base
  after_initialize :init

  def init
    self.value = 15_00
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :init

  has_many :wikis, dependent: :destroy

  def init
    self.role ||= :member
  end

  enum role: [:member, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Membership",
      amount: Amount.new.value
    }
  end

  def create
    #Creates a Stripe Customer object for associating with charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.new.value,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, bruh! Keep it coming!"
    current_user.premium!
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def destroy
    flash[:alert] = "YOUR ACCOUNT HAS BEEN DOWNGRADED, YUNG BLOC"
    current_user.member!
    current_user.wikis.update_all(private: false)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authorize_user, except: [:index, :show, :edit, :update, :new, :create]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user_id = current_user.id
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "It's lit fam."
      redirect_to @wiki
    else
      flash[:alert] = "This is WRONG"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(params[:wiki][:body])
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Ya update was saved, bruh."
      redirect_to @wiki
    else
      flash[:alert] = "Nope."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "IT'S GONE. IT'S ALL GONE."
      redirect_to wikis_path
    else
      flash[:alert] = "WE CANNOT BE DESTROYED"
      render :show
    end
  end

  def authorize_user
    unless current_user.admin? || current_user.premium?
      flash[:alert] = "YOU CAN'T DO THAT"
      redirect_to wikis_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Time to upgrade!</h4>
  <p>That'll be $15.00. You have to pay with a card. This is the internet.</p>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class = "nav nav-tabs">
       <li><%= link_to "Home", welcome_index_path %></li>
       <li><%= link_to "Wikis", wikis_path %></li>
       <div class="pull-right user-info">
         <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
         <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
       </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

<%= yield %>
  </div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Blocipedia is a resource for sharing links with your friends!</p>
  <p>
    
  </p>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>Solves world hunger</h2>
    <p>Blocipedia will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-6">
    <h2>Eliminates poverty</h2>
    <p>Blocipedia will deliver money and education to those in need, all over the world.</p>
  </div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= form_for @wiki do |f| %>
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Ya Wiki, bruh</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
        <%= render partial: 'wikis/form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-3">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Let's Make A Wiki!</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
        <%= render partial: 'wikis/form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @wiki.body.html_safe %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if current_user && current_user.admin? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    <% end %>
  </div>
</div>